replicaCount: 1

image:
  repository: jecklgamis/langgraph-example
  tag: "main"
  pullPolicy: Always

imagePullSecrets:
  - name: dockerhub

service:
  type: ClusterIP
  port: 8000

ingress:
  enabled: true
  className: "nginx"
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
    cert-manager.io/issuer: "letsencrypt-prod"
    nginx.ingress.kubernetes.io/proxy-read-timeout: "600"
  hosts:
    - host: langgraph-example.jecklgamis.com
      paths:
        - path: /
          pathType: Prefix
  tls:
    - secretName: langgraph-example.jecklgamis.com
      hosts:
        - langgraph-example.jecklgamis.com

resources:
  requests:
    cpu: 250m
    memory: 256Mi
  limits:
    cpu: 1000m
    memory: 1Gi

autoscaling:
  enabled: false
  minReplicas: 1
  maxReplicas: 2
  targetCPUUtilizationPercentage: 80

env:
  LLM_PROVIDER: "gemini"
  GUARDRAILS_ENABLED: "true"
  HUMAN_IN_LOOP: "false"

secrets:
  OPENAI_API_KEY: ""
  GEMINI_API_KEY: ""
  ANTHROPIC_API_KEY: ""
  AZURE_OPENAI_API_KEY: ""
  AZURE_OPENAI_ENDPOINT: ""
  LLAMA_API_KEY: ""
  DEEPSEEK_API_KEY: ""
  MISTRAL_API_KEY: ""
  XAI_API_KEY: ""
  OPENROUTER_API_KEY: ""
  LANGCHAIN_API_KEY: ""
